### ISSUE TITLE
使用app.mongo.aggregate 报错

### ISSUE THREAD

**Issue by Faynman-Dragon** [brickyang/egg-mongo-native#10]
调用方法：
`var args = [{ $match: {} },{$group: {_id: "max", max_value: {$max: "$id"}}}];
 const [result] = await app.mongo.aggregate("member", {args});`

报错信息：
TypeError: Cannot read property '$out' of undefined
    at Collection.aggregate (E:\workspace\projects\demo\egg-example\node_modules\_mongodb@3.0.4@mongodb\lib\collection.js:2455:66)
    at MongoDB.aggregate (E:\workspace\projects\demo\egg-example\node_modules\_egg-mongo-native@3.0.0@egg-mongo-native\lib\mongo.js:530:8)

**Comment by brickyang** [comment]
```javascript
const [result] = await app.mongo.aggregate("member", {pipeline: args});
```
