### ISSUE TITLE
3.4 版本变更是否引入了不兼容元素？

### ISSUE THREAD

**Issue by kasora** [brickyang/egg-mongo-native#32]
由于使用了 `^3.3.0` 版本，新版本 release 后 ci 跑测试失败。
配置格式为
```js
  // config.unittest.ts
  config.mongo = {
    client: {
      host: 'xxxxx.com.cn',
      port: '12450',
      name: 'xxxxx',
      user: 'xxxx',
      password: 'pwd',
      options: {},
    },
  };
```
错误信息为：
``` 
MongoError: not authorized on admin to execute command { getParameter: 1, featureCompatibilityVersion: 1 }
      at /node_modules/_mongodb-core@3.1.11@mongodb-core/lib/connection/pool.js:581:63
      at authenticateStragglers (node_modules/_mongodb-core@3.1.11@mongodb-core/lib/connection/pool.js:504:16)
      at Connection.messageHandler (node_modules/_mongodb-core@3.1.11@mongodb-core/lib/connection/pool.js:540:5)
      at emitMessageHandler (node_modules/_mongodb-core@3.1.11@mongodb-core/lib/connection/connection.js:310:10)
      at Socket.<anonymous> (node_modules/_mongodb-core@3.1.11@mongodb-core/lib/connection/connection.js:453:17)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:607:20)
```
随后锁定版本为 `3.3.0` 则恢复正常。
是否新 release 引入了不兼容元素？

**Comment by brickyang** [comment]
你的 MongoDB 数据库版本是？

**Comment by kasora** [comment]
@brickyang  v3.4.14

**Comment by brickyang** [comment]
看错误信息是用户没有权限执行 `{ getParameter: 1, featureCompatibilityVersion: 1 }` 命令。

因为新增的部分功能对数据库版本有要求，所以在连接时运行了该命令检查数据库功能兼容性。发一个布丁版本取消该命令吧。

**Comment by brickyang** [comment]
这个问题其实存在于 [easy-mongodb](https://github.com/brickyang/easy-mongodb) 中，现在已经发了新版（1.1.2）。

本地只要没有锁版本，重新安装 `egg-mongo-native` 正常就会下载最新的依赖包。

**Comment by kasora** [comment]
好的。感谢！
